WEAVIATE_URL = 'https://rag-chain-5apxq0sp.weaviate.network'
FEEDBACK_URL = 'https://feedback-rag-k241tzi1.weaviate.network'
FEEDBACK_API = 'Sa3HT5HuewWaTLDoEyjkNDoawvtkxNj5bH46'
WEAVIATE_V_KEY = '3UH4dhZe4z1MFyOJ2Vk9lVECqzYbP0bjpj5h'
GPT_KEY = 'sk-proj-PMJ67akceG4mbeOTbBJVT3BlbkFJvLd9KWYTh4NKefAWfvl8'
IMAGE_URL = 'https://w1b3cg8prsajegpey4oxdq.c0.europe-west3.gcp.weaviate.cloud'
IMAGE_API = 'qB3Kgii3IzY3fmFMPpOU7Dk2K1wHiBYfdFzE'
TEXT_URL = 'https://lhmf46ciswsitpb7geuw.c0.europe-west3.gcp.weaviate.cloud'
TEXT_API = 'Y4IdgBpmXKrWaLulOvbNsdBMuvKlwRM9VTSD'
HUGGINGFACEHUB_API_TOKEN = "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"
LANGSMITH_API_KEY = "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"
LANGSMITH_URL = "https://api.smith.langchain.com"
PINECONE_API_KEY = 'b8d257bf-cb1a-4b8e-984b-c2f264a5eb51'
FEEDBACK_API_KEY = 'a04bcb29-2d7d-48bd-9142-c60b28b765e1'
LANGCHAIN_PROJECT = "evaluator"
LANGSMITH_RUN_ID = 'e4e4cef3-9bf8-431e-baf1-b250fbf51165'